### ISSUE TITLE
Error when player killed with TnT while PvP off

### ISSUE THREAD

**Issue by Strahilchu** [Lqminescence/TogglePVP#1]
This is the console error I got when I killed someone with TnT and PvP was off
I really love this plugin, I am on 1.16.4 Paper
Please please fix <3

[13:42:15 ERROR]: Could not pass event EntityDamageByEntityEvent to TogglePVP v1.0-SNAPSHOT
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.entity.CraftTNTPrimed cannot be cast to class org.bukkit.entity.Player (org.bukkit.craftbukkit.v1_16_R3.entity.CraftTNTPrimed and org.bukkit.entity.Player are in unnamed module of loader 'app')
        at me.luminescence.togglepvp.PVPListener.onAttack(PVPListener.java:19) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor26.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-350]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-350]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-350]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-350]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:252) ~[patched_1.16.4.jar:git-Paper-350]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:912) ~[patched_1.16.4.jar:git-Paper-350]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:889) ~[patched_1.16.4.jar:git-Paper-350]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1078) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1830) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:844) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1165) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:844) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.Explosion.a(Explosion.java:193) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.World.createExplosion(World.java:916) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.WorldServer.createExplosion(WorldServer.java:1605) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.World.createExplosion(World.java:910) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.EntityTNTPrimed.explode(EntityTNTPrimed.java:114) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.EntityTNTPrimed.tick(EntityTNTPrimed.java:73) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:845) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.World.a(World.java:884) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:530) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1356) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-350]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-350]
        at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by Strahilchu** [comment]
Also does this if killed by End Crystal
